name: Check #name github action
on: 
  push:
    branches: ['master']
jobs:
  test: # название джобы
    runs-on: ubuntu-latest
    steps: # Перечень шагов, которые необходимо выполнить в рамках джобы.
      - name: cd into repo # Название шага
        uses: actions/checkout@v3

      - name: install java and maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: run tests
        run: mvn test

